version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"